### ISSUE TITLE
Decide on email format for game

### ISSUE THREAD

**Issue by jrans** [jrans/check-mail#3]
This includes the title and message body.

+ [x] Move in the title?
+ [ ] Updated board each time?
+ [ ] Notation in full.
+ [ ] Messages between players.
+ [x] Standard format to parse.

Link to red sift if person doesn't have it?

**Comment by jrans** [comment]
title must include `[check-mail]` and messages must have a move like  `[ e4 ] good luck! ...`
